### ISSUE TITLE
How to fix matplotlib animation issue: 'TimerWasm' object has no attribute '_timer' 

### ISSUE THREAD

**Issue by xtong** [gzuidhof/starboard-notebook#22]
Dear,

I tried matplotlib animation in starboard-notebook, but encountered the following error:

Python exception: 
Traceback (most recent call last): 
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 70, in eval_code 
    eval(compile(mod, "<exec>", mode="exec"), ns, ns) 
  File "<exec>", line 22, in <module> 
  File "/lib/python3.8/site-packages/matplotlib/animation.py", line 1484, in __init__ 
    TimedAnimation.__init__(self, fig, *args, **kwargs) 
  File "/lib/python3.8/site-packages/matplotlib/animation.py", line 1414, in __init__ 
    event_source = fig.canvas.new_timer(interval=self._interval) 
  File "/lib/python3.8/site-packages/matplotlib/backends/wasm_backend.py", line 452, in new_timer 
    return TimerWasm(*args, **kwargs) 
  File "/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1093, in __init__ 
    self.interval = 1000 if interval is None else interval 
  File "/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1135, in interval 
    self._timer_set_interval() 
  File "/lib/python3.8/site-packages/matplotlib/backends/wasm_backend.py", line 581, in _timer_set_interval 
    if self._timer is not None: 
AttributeError: 'TimerWasm' object has no attribute '_timer' 

Could you please help me advise this? Thanks!

Attached the sample code for your reference:

import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib.animation as animation

fig, ax = plt.subplots()

def f(x, y):
    return np.sin(x) + np.cos(y)

x = np.linspace(0, 2 * np.pi, 120)
y = np.linspace(0, 2 * np.pi, 100).reshape(-1, 1)

ims = []
for i in range(60):
    x += np.pi / 15.
    y += np.pi / 20.
    im = ax.imshow(f(x, y), animated = True)
    if i == 0:
        ax.imshow(f(x, y))
    ims.append([im])

ani = animation.ArtistAnimation(fig = fig, artists = ims, interval = 200, repeat_delay = 0, blit = True, repeat = False)

plt.show()

**Comment by gzuidhof** [comment]
Hi xtong,

This question may be better in the Pyodide repository, but I am afraid that it has to do with Python in the browser being entirely synchronous. That means there are no "timers", you can't use "sleep", or have asynchronous code.

You can have timers and asynchronous code in Javascript however, so you could trigger Python functions from that to update your plot, but I'm afraid that out of the box the animation  library of matplotlib will not work :(. 

There are some people trying to get asynchronous Python work in WebAssembly which would solve this, so maybe one day.
